(() => {
const ENEMY_DECK = [
  // ========== 階層 1：草原與初級洞窟 ==========
  {
    id: 'giant_mallet',
    tier: 1,
    monsterType: 'attack',
    name: '大木槌',
    flavor: '手持巨大木槌，攻擊力在初期算高，會痛恨一擊。',
    emoji: '🔨',
    sizeLevel: 2, // 80% - 中等大小
    baseXp: 12,
    baseHp: 13,
    baseMp: 0,
    baseAttributes: {
      attack: 15,
      vitality: 5,
      defense: 2,
      recovery: 8,
      magic: 8,
      agility: 3,
    },
    growthPerLevel: {
      attack: 5.5,
      vitality: 3,
      defense: 4.0,
      recovery: 2.2,
      magic: 2.1,
      agility: 0.5,
    },
    skills: [
      { id: 'slash_1', probability: 0.2 },
    ],
    goldDrop: 10,
    },
  {
    id: 'iron_ant',
    tier: 1,
    monsterType: 'defense',
    name: '鐵甲蟻',
    flavor: '外殼堅硬，物理防禦力高，新手武器難以造成大傷害。',
    emoji: '🐜',
    sizeLevel: 1, // 60% - 小怪物
    baseXp: 15,
    baseHp: 15,
    baseMp: 0,
    baseAttributes: {
      attack: 12,
      vitality: 8,
      defense: 10,
      recovery: 0,
      magic: 1,
      agility: 2,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 2,
      defense: 5.0,
      recovery: 0.3,
      magic: 0.1,
      agility: 0.3,
    },
    skills: [
      { id: 'defense_shield_t1', probability: 0.2 },
    ],
    goldDrop: 10,
    },
  {
    id: 'dracky',
    tier: 1,
    monsterType: 'magic',
    name: '多拉奇',
    flavor: '著名的蝙蝠怪，會施放美拉(小火球)。',
    emoji: '🦇',
    sizeLevel: 1, // 60% - 小怪物
    baseXp: 11,
    baseHp: 11,
    baseMp: 2,
    baseAttributes: {
      attack: 11,
      vitality: 5,
      defense: 4,
      recovery: 9,
      magic: 4, 
      agility: 6,
    },
    growthPerLevel: {
      attack: 4.0,
      vitality: 3,
      defense: 4.0,
      recovery: 2.3,
      magic: 4.0,
      agility: 1.5,
    },
    skills: [
      { id: 'fireball_1', probability: 0.8 },
    ],
    goldDrop: 10,
    },
  {
    id: 'stump_chump',
    tier: 1,
    monsterType: 'recovery',
    name: '樹樁怪',
    flavor: '雖然是植物，但常會使用藥草替自己或同伴補血。',
    emoji: '🪵',
    sizeLevel: 2, // 80% - 中等大小
    baseXp: 14,
    baseHp: 15,
    baseMp: 6,
    baseAttributes: {
      attack: 13,
      vitality: 4,
      defense: 5,
      recovery: 10,
      magic: 10,
      agility: 2,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 3.0,
      defense: 3.8,
      recovery: 2.0,
      magic: 1.8,
      agility: 0.3,
    },
    skills: [
      { id: 'heal_1', probability: 0.4 },
    ],
    goldDrop: 10,
    },
  {
    id: 'bunnycorn',
    tier: 1,
    monsterType: 'agile',
    name: '一角兔',
    flavor: '速度比主角快，常會搶先攻擊。',
    emoji: '🐰',
    sizeLevel: 1, // 60% - 小怪物
    baseXp: 14,
    baseHp: 12,
    baseMp: 2,
    baseAttributes: {
      attack: 8,
      vitality: 3,
      defense: 4,
      recovery: 2,
      magic: 1,
      agility: 9,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 1.5,
      defense: 3.5,
      recovery: 1,
      magic: 1,
      agility: 3.0,
    },
    skills: [
      { id: 'slash_1', probability: 0.2 },
    ],
    goldDrop: 10,
    },
  {
    id: 'slime',
    tier: 1,
    monsterType: 'average',
    name: '史萊姆',
    flavor: '永遠的吉祥物，各項數值平均偏低，最適合練功。',
    emoji: '🟦',
    sizeLevel: 1, // 60% - 小怪物
    baseXp: 10,
    baseHp: 10,
    baseMp: 0,
    baseAttributes: {
      attack: 9,
      vitality: 5,
      defense: 6,
      recovery: 7,
      magic: 8,
      agility: 5,
    },
    growthPerLevel: {
      attack:  4,
      vitality: 3,
      defense:  4,
      recovery:  2.2,
      magic:  2.0,
      agility:  1.0,
    },
    skills: [],
    goldDrop: 10,
    },
  {
    id: 'green_dragon',
    tier: 1,
    monsterType: 'boss',
    name: '綠龍',
    flavor: '初期的強敵，會吐出火燄吐息，血量是雜魚的好幾倍。',
    emoji: '🐉',
    sizeLevel: 4, // 120% - 大型boss
    baseXp: 30,
    baseHp: 100,
    baseMp: 25,
    baseAttributes: {
      attack: 15,
      vitality: 10,
      defense: 10,
      recovery: 10,
      magic: 10,
      agility: 10,
    },
    growthPerLevel: {
      attack: 4.2,
      vitality: 3.0,
      defense: 4.2,
      recovery: 3.0,
      magic: 2.5,
      agility: 1.5,
    },
    skills: [
      { id: 'fireball_1', probability: 0.4 },
      { id: 'slash_1', probability: 0.3 },
    ],
    goldDrop: 100,
    },
  
  // ========== 階層 2：荒野與高塔 ==========
  {
    id: 'skeleton',
    tier: 2,
    monsterType: 'attack',
    name: '骷髏',
    flavor: '不死系戰士，攻擊力與揮劍頻率都比初期怪物高。',
    emoji: '💀',
    sizeLevel: 2, // 100% - 正常大小
    baseXp: 16,
    baseHp: 80,
    baseMp: 0,
    baseAttributes: {
      attack: 20,
      vitality: 10,
      defense: 10,
      recovery: 3,
      magic: 2,
      agility: 6,
    },
    growthPerLevel: {
      attack: 5,
      vitality: 3.0,
      defense: 4.5,
      recovery: 0.4,
      magic: 0.3,
      agility: 2.0,
    },
    skills: [],
    goldDrop: 30,
    },
  {
    id: 'walking_corpse',
    tier: 2,
    monsterType: 'defense',
    name: '腐爛屍體',
    flavor: 'HP非常高，且防禦力不錯，還有毒攻擊，很難快速擊倒。',
    emoji: '🧟',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 14,
    baseHp: 90,
    baseMp: 5,
    baseAttributes: {
      attack: 20,
      vitality: 10,
      defense: 15,
      recovery: 5,
      magic: 3,
      agility: 30,
    },
    growthPerLevel: {
      attack: 4,
      vitality: 4,
      defense: 4,
      recovery: 1.0,
      magic: 0.5,
      agility: 1,
    },
    skills: [
      { id: 'poison_attack_1', probability: 0.9 },
    ],
    goldDrop: 30,
    },
  {
    id: 'imp',
    tier: 2,
    monsterType: 'magic',
    name: '小惡魔',
    flavor: '會使用美拉米或冰系咒文，MP量在初期算多。',
    emoji: '😈',
    sizeLevel: 3, // 60% - 小怪物
    baseXp: 12,
    baseHp: 70,
    baseMp: 25,
    baseAttributes: {
      attack: 19,
      vitality: 18,
      defense: 19,
      recovery: 10,
      magic: 20,
      agility: 8,
    },
    growthPerLevel: {
      attack: 3.5,
      vitality: 3.0,
      defense: 4.4,
      recovery: 0.5,
      magic: 3.5,
      agility: 4.5,
    },
    skills: [
      { id: 'fireball_1', probability: 0.25 },
      { id: 'acid_arrow_1', probability: 0.25 },
      { id: 'iceball_1', probability: 0.25},
    ],
    goldDrop: 40,
    },
  {
    id: 'healslime',
    tier: 2,
    monsterType: 'recovery',
    name: '荷伊米史萊姆',
    flavor: '經典補師，總是漂浮在空中幫其他強力怪物補血。',
    emoji: '💚',
    sizeLevel: 2, // 60% - 小怪物
    baseXp: 11,
    baseHp: 70,
    baseMp: 25,
    baseAttributes: {
      attack: 11,
      vitality: 15,
      defense: 10,
      recovery: 15,
      magic: 8,
      agility: 5,
    },
    growthPerLevel: {
      attack: 4.1,
      vitality: 2.5,
      defense: 4.3,
      recovery: 2.5,
      magic: 1.5,
      agility: 0.8,
    },
    skills: [
      { id: 'heal_1', probability: 0.2 },
      { id: 'heal_2', probability: 0.2 },
    ],
    goldDrop: 25,
    },
  {
    id: 'chimera',
    tier: 2,
    monsterType: 'agile',
    name: '奇美拉',
    flavor: '速度極快，會噴火，甚至會用路拉(傳送)逃跑。',
    emoji: '🦁',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 16,
    baseHp: 70,
    baseMp: 10,
    baseAttributes: {
      attack: 11,
      vitality: 10,
      defense: 10,
      recovery: 20,
      magic: 10,
      agility: 18,
    },
    growthPerLevel: {
      attack:  5,
      vitality: 3.1,
      defense: 4.5,
      recovery: 2.5,
      magic: 3.0,
      agility: 3.6,
    },
    skills: [
      { id: 'slash_2', probability: 0.2 },
      { id: 'fireball_1', probability: 0.2 },
    ],
    goldDrop: 40,
    },
  {
    id: 'she_slime',
    tier: 2,
    monsterType: 'average',
    name: '史萊姆貝斯',
    flavor: '橘紅色的史萊姆，攻擊與防禦都比藍色史萊姆高一階。',
    emoji: '🟧',
    sizeLevel: 2, // 80% - 中等大小
    baseXp: 14,
    baseHp: 55,
    baseMp: 8,
    baseAttributes: {
      attack: 21,
      vitality: 10,
      defense: 10,
      recovery: 5,
      magic: 6,
      agility: 8,
    },
    growthPerLevel: {
      attack: 4.2,
      vitality: 1.8,
      defense: 4.2,
      recovery: 1.0,
      magic: 1.2,
      agility: 1.5,
    },
    skills: [
      { id: 'slash_2', probability: 0.8 },
    ],
    goldDrop: 20,
    },
  {
    id: 'kandar',
    tier: 2,
    monsterType: 'boss',
    name: '干達坦',
    flavor: '盜賊頭目，攻擊力強且會帶小弟，經典的中頭目。',
    emoji: '🗡️👑',
    sizeLevel: 3, // 100% - boss但不算特别大
    baseXp: 50,
    baseHp: 600,
    baseMp: 50,
    baseAttributes: {
      attack: 50,
      vitality: 35,
      defense: 15,
      recovery: 1,
      magic: 1,
      agility: 20,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 4.0,
      defense: 4.4,
      recovery: 1.0,
      magic: 1.0,
      agility: 2.0,
    },
    skills: [
      { id: 'agility_strike_1', probability: 0.2 },
      { id: 'poison_attack_1', probability: 0.3 },
      { id: 'rapid_strike_2', probability: 0.3 },
    ],
    goldDrop: 100,
    },
  
  // ========== 階層 3：海洋與沙漠 ==========
  {
    id: 'hammerhood',
    tier: 3,
    monsterType: 'attack',
    name: '褐猿',
    flavor: '蓄力攻擊非常痛，是中期物理輸出的代表。',
    emoji: '🦍',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 26,
    baseHp: 80,
    baseMp: 18,
    baseAttributes: {
      attack: 48,
      vitality: 18,
      defense: 32,
      recovery: 4,
      magic: 3,
      agility: 10,
    },
    growthPerLevel: {
      attack: 4.7,
      vitality: 4.0,
      defense: 4.0,
      recovery: 0.8,
      magic: 0.5,
      agility: 2.0,
    },
    skills: [
      { id: 'sword_intent_2', probability: 0.3 },
      { id: 'slash_2', probability: 0.3 },
    ],
    goldDrop: 30,
    },
  {
    id: 'rockbomb',
    tier: 3,
    monsterType: 'defense',
    name: '爆彈岩',
    flavor: '防禦極高，平時不攻擊，但HP低時會用「美干手」自爆全滅隊伍。',
    emoji: '💣',
    sizeLevel: 2, // 80% - 中等大小
    baseXp: 27,
    baseHp: 100,
    baseMp: 15,
    baseAttributes: {
      attack: 33,
      vitality: 30,
      defense: 40,
      recovery: 25,
      magic: 35,
      agility: 2,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 4.0,
      defense: 4.3,
      recovery: 1.0,
      magic: 3.0,
      agility: 0.4,
    },
    skills: [
      { id: 'defense_shield_t2', probability: 0.1 },
      { id: 'explosion_2', probability: 0.3 },
    ],
    goldDrop: 20,
    },
  {
    id: 'goodybag',
    tier: 3,
    monsterType: 'magic',
    name: '跳舞寶石',
    flavor: 'MP很高，會使用奇怪的舞蹈封鎖玩家行動或降防。',
    emoji: '💎',
    sizeLevel: 1, // 60% - 小怪物
    baseXp: 20,
    baseHp: 120,
    baseMp: 100,
    baseAttributes: {
      attack: 28,
      vitality: 22,
      defense: 28,
      recovery: 12,
      magic: 12,
      agility: 12,
    },
    growthPerLevel: {
      attack: 4.3,
      vitality: 4.0,
      defense: 4.0,
      recovery: 3.5,
      magic: 3.5,
      agility: 2.5,
    },
    skills: [
      { id: 'fireball_2', probability: 0.3 },
      { id: 'acid_arrow_2', probability: 0.25 },
      { id: 'iceball_2', probability: 0.25 },
      { id: 'mass_heal_1', probability: 0.2 },
    ],
    goldDrop: 60,
    },
  {
    id: 'orc',
    tier: 3,
    monsterType: 'recovery',
    name: '半獸人',
    flavor: '體力好且會使用霍伊米或貝霍伊米，生存力強的補師。',
    emoji: '👹',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 21,
    baseHp: 160,
    baseMp: 35,
    baseAttributes: {
      attack: 32,
      vitality: 22,
      defense: 26,
      recovery: 20,
      magic: 12,
      agility: 6,
    },
    growthPerLevel: {
      attack: 4.0,
      vitality: 5.0,
      defense: 4.0,
      recovery: 4.0,
      magic: 2.5,
      agility: 1.2,
    },
    skills: [
      { id: 'heal_2', probability: 0.2 },
      { id: 'mass_heal_1', probability: 0.2 },
    ],
    goldDrop: 40,
    },
  {
    id: 'killer_panther',
    tier: 3,
    monsterType: 'agile',
    name: '殺人豹',
    flavor: '速度極快，高機率一回合行動兩次或發動痛恨一擊。',
    emoji: '🐆',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 23,
    baseHp: 130,
    baseMp: 10,
    baseAttributes: {
      attack: 48,
      vitality: 15,
      defense: 30,
      recovery: 4,
      magic: 5,
      agility: 28,
    },
    growthPerLevel: {
      attack: 4.4,
      vitality: 3.5,
      defense: 3.5,
      recovery: 0.8,
      magic: 1.0,
      agility: 5.5,
    },
    skills: [
      { id: 'agility_strike_2', probability: 0.3 },
      { id: 'poison_attack_2', probability: 0.3 },
    ],
    goldDrop: 40,
    },
  {
    id: 'slime_knight',
    tier: 3,
    monsterType: 'average',
    name: '史萊姆騎士',
    flavor: '攻守兼備，會補血也會物理攻擊，最平衡的騎士。',
    emoji: '🛡️🟦',
    sizeLevel: 2, // 80% - 中等大小
    baseXp: 25,
    baseHp: 140,
    baseMp: 20,
    baseAttributes: {
      attack: 30,
      vitality: 18,
      defense: 30,
      recovery: 16,
      magic: 1,
      agility: 12,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 3.8,
      defense: 4.2,
      recovery: 3.5,
      magic: 1.0,
      agility: 1.5,
    },
    skills: [
      { id: 'slash_2', probability: 0.3 },
      { id: 'heal_2', probability: 0.3 },
    ],
    goldDrop: 40,
    },
  {
    id: 'orochi',
    tier: 3,
    monsterType: 'boss',
    name: '八歧大蛇',
    flavor: '巨大的多頭龍，連續兩次行動與強烈的全體火焰吐息。',
    emoji: '🐉🐉🐉',
    actionsPerTurn: 2, // 每回合行動2次
    sizeLevel: 4, // 120% - 大型boss
    baseXp: 120,
    baseHp: 1500,
    baseMp: 150,
    baseAttributes: {
      attack: 60,
      vitality: 60,
      defense: 50,
      recovery: 30,
      magic: 55,
      agility: 18,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 4.5,
      defense: 4.5,
      recovery: 4.5,
      magic: 4.5,
      agility: 3.0,
    },
    skills: [
      { id: 'acid_arrow_1', probability: 0.15 },
      { id: 'lightning_chain_1', probability: 0.15 },
      { id: 'rapidity_strike_1', probability: 0.14 },
      { id: 'fireball_2', probability: 0.14 },
      { id: 'explosion_1', probability: 0.16 },
    ],
    goldDrop: 200,
    },
  
  // ========== 階層 4：魔界外圍與城堡 ==========
  {
    id: 'troll',
    tier: 4,
    monsterType: 'attack',
    name: '食人魔',
    flavor: '巨大的身軀與木棒，每一擊都極具破壞力，暴擊率高。',
    emoji: '👺',
    sizeLevel: 4, // 120% - 大型怪物
    baseXp: 32,
    baseHp: 200,
    baseMp: 8,
    baseAttributes: {
      attack:120,
      vitality: 25,
      defense: 60,
      recovery: 5,
      magic: 4,
      agility: 12,
    },
    growthPerLevel: {
      attack: 5.0,
      vitality: 4.0,
      defense: 4.0,
      recovery: 1.0,
      magic: 0.8,
      agility: 2.5,
    },
    skills: [
    ],
    goldDrop: 60,
    },
  {
    id: 'living_statue',
    tier: 4,
    monsterType: 'defense',
    name: '動石像',
    flavor: '彷彿堡壘般的防禦力，對魔法也有一定抗性，還會踩踏全體。',
    emoji: '🗿',
    sizeLevel: 4, // 120% - 大型怪物
    baseXp: 31,
    baseHp: 300,
    baseMp: 10,
    baseAttributes: {
      attack: 80,
      vitality: 30,
      defense: 75,
      recovery: 98,
      magic: 128,
      agility: 5,
    },
    growthPerLevel: {
      attack: 4.3,
      vitality: 4.8,
      defense: 4.5,
      recovery: 3.5,
      magic: 3.5,
      agility: 1.0,
    },
    skills: [
      { id: 'defense_shield_t3', probability: 0.2 },
      { id: 'sword_wave_2', probability: 0.2 },
    ],
    goldDrop: 60,
    },
  {
    id: 'archdemon',
    tier: 4,
    monsterType: 'magic',
    name: '大惡魔',
    flavor: '會使用伊奧那(大爆炸)等高階全體魔法。',
    emoji: '😈👑',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 39,
    baseHp: 300,
    baseMp: 60,
    baseAttributes: {
      attack: 42,
      vitality: 18,
      defense: 42,
      recovery: 8,
      magic: 92,
      agility: 25,
    },
    growthPerLevel: {
      attack: 4.0,
      vitality: 3.0,
      defense: 4.0,
      recovery: 2.5,
      magic: 6.5,
      agility: 3.5,
    },
    skills: [
      { id: 'fireball_2', probability: 0.4 },
      { id: 'explosion_2', probability: 0.3 },
    ],
    goldDrop: 80,
    },
  {
    id: 'orc_king',
    tier: 4,
    monsterType: 'recovery',
    name: '半獸人王',
    flavor: '擁有查奧里克(復活)與全體補血，不先打倒他戰鬥會沒完沒了。',
    emoji: '👑👹',
    sizeLevel: 4, // 120% - 大型boss
    baseXp: 32,
    baseHp: 300,
    baseMp: 50,
    baseAttributes: {
      attack: 78,
      vitality: 35,
      defense: 48,
      recovery: 38,
      magic: 18,
      agility: 10,
    },
    growthPerLevel: {
      attack: 4.0,
      vitality: 5.0,
      defense: 3.8,
      recovery: 3.5,
      magic: 1.5,
      agility: 2.0,
    },
    skills: [
      { id: 'mass_heal_1', probability: 0.3 },
      { id: 'revive_companion', probability: 0.1 },
    ],
    goldDrop: 80,
    },
  {
    id: 'gargoyle',
    tier: 4,
    monsterType: 'agile',
    name: '石像鬼',
    flavor: '速度快且會使用催眠咒文，常讓玩家隊伍陷入睡眠後滅團。',
    emoji: '🦅',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 35,
    baseHp: 300,
    baseMp: 25,
    baseAttributes: {
      attack: 70,
      vitality: 20,
      defense: 45,
      recovery: 6,
      magic: 15,
      agility: 95,
    },
    growthPerLevel: {
      attack: 4.0,
      vitality: 4.0,
      defense: 4.0,
      recovery: 1.2,
      magic: 3.0,
      agility: 3.6,
    },
    skills: [
       { id: 'acid_arrow_1', probability: 0.2 },
      { id: 'agility_strike_2', probability: 0.2 },
      { id: 'rapidity_strike_3', probability: 0.2 },
    ],
    goldDrop: 80,
    },
  {
    id: 'king_slime',
    tier: 4,
    monsterType: 'average',
    name: '史萊姆王',
    flavor: '體型巨大，HP高，會使用美拉米與壓扁攻擊。',
    emoji: '👑🟦',
    sizeLevel: 4, // 120% - 大型怪物（體型巨大）
    baseXp: 32,
    baseHp: 360,
    baseMp: 30,
    baseAttributes: {
      attack: 95,
      vitality: 68,
      defense: 40,
      recovery: 55,
      magic: 66,
      agility: 15,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 3.2,
      defense: 4.0,
      recovery: 3.0,
      magic: 3.2,
      agility: 3.0,
    },
    skills: [
      { id: 'slash_2', probability: 0.3 },
      { id: 'fireball_2', probability: 0.3 },
      { id: 'mass_heal_1', probability: 0.3 },
    ],
    goldDrop: 80,
    },
  {
    id: 'baramos',
    tier: 4,
    monsterType: 'boss',
    name: '巴拉摩斯',
    flavor: '魔王級別，強力的伊奧納茲恩(極大爆炸)與混亂咒文。',
    emoji: '👑😈',
    sizeLevel: 4, // 120% - 大型boss
    baseXp: 300,
    baseHp: 3500,
    baseMp: 250,
    actionsPerTurn: 2, // 每回合行動2次
    baseAttributes: {
      attack: 100,
      vitality: 70,
      defense: 60,
      recovery: 150,
      magic: 180,
      agility: 25,
    },
    growthPerLevel: {
      attack: 3.7,
      vitality: 5.0,
      defense: 3.6,
      recovery: 4.0,
      magic: 5.2,
      agility: 3.0,
    },
    skills: [
      { id: 'fireball_5', probability: 0.33 },
      { id: 'heal_4', probability: 0.25 },
      { id: 'explosion_3', probability: 0.2 },
    ],
    goldDrop: 400,
    },
  
  // ========== 階層 5：最終迷宮 ==========
  {
    id: 'gigantes',
    tier: 5,
    monsterType: 'attack',
    name: '巨人',
    flavor: '擁有壓倒性的攻擊力，普通攻擊就能造成瀕死傷害。',
    emoji: '👹',
    sizeLevel: 4, // 120% - 大型怪物（巨人）
    baseXp: 60,
    baseHp: 500,
    baseMp: 10,
    baseAttributes: {
      attack: 130,
      vitality: 45,
      defense: 100,
      recovery: 6,
      magic: 5,
      agility: 15,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 4.0,
      defense: 4.0,
      recovery: 1.2,
      magic: 1.0,
      agility: 2.0,
    },
    skills: [
    ],
    goldDrop: 160,
    },
  {
    id: 'killing_machine',
    tier: 5,
    monsterType: 'defense',
    name: '殺人機器',
    flavor: '鋼鐵身軀免疫毒與麻痺，可連續攻擊兩次，無情的殺戮者。',
    emoji: '🤖',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 50,
    baseHp: 400,
    baseMp: 35,
    baseAttributes: {
      attack: 105,
      vitality: 55,
      defense: 98,
      recovery: 10,
      magic: 10,
      agility: 8,
    },
    growthPerLevel: {
      attack: 4.2,
      vitality: 4.0,
      defense: 4.0,
      recovery: 3.0,
      magic: 2.0,
      agility: 1.5,
    },
    skills: [
      { id: 'rapidity_strike_3', probability: 0.3 },
      { id: 'sword_wave_2', probability: 0.2},
    ],
    goldDrop: 160,
    },
  {
    id: 'great_dragon',
    tier: 5,
    monsterType: 'magic',
    name: '巨龍',
    flavor: '吐出最高級的灼熱火焰或冰凍吐息，魔法抗性極強。',
    emoji: '🐉🔥',
    sizeLevel: 4, // 120% - 大型怪物（巨龍）
    baseXp: 57,
    baseHp: 440,
    baseMp: 80,
    baseAttributes: {
      attack: 98,
      vitality: 25,
      defense: 108,
      recovery: 100,
      magic: 95,
      agility: 18,
    },
    growthPerLevel: {
      attack: 3.5,
      vitality: 3.5,
      defense: 3.5,
      recovery: 4.0,
      magic: 4.0,
      agility: 2.5,
    },
    skills: [
      { id: 'fireball_3', probability: 0.3 },
      { id: 'explosion_3', probability: 0.3 },
    ],
    goldDrop: 160,
    },
  {
    id: 'fallen_priest',
    tier: 5,
    monsterType: 'recovery',
    name: '惡魔神官',
    flavor: '既會使用最高級攻擊魔法，也會完全恢復HP與復活隊友。',
    emoji: '👤🔮',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 58,
    baseHp: 320,
    baseMp: 70,
    baseAttributes: {
      attack: 105,
      vitality: 45,
      defense: 92,
      recovery: 38,
      magic: 58,
      agility: 12,
    },
    growthPerLevel: {
      attack: 4.2,
      vitality: 4.0,
      defense: 4.0,
      recovery: 7.5,
      magic: 5.5,
      agility: 2.5,
    },
    skills: [
      { id: 'fireball_5', probability: 0.2 },
      { id: 'heal_5', probability: 0.2 },
    ],
    goldDrop: 160,
    },
  {
    id: 'bone_baron',
    tier: 5,
    monsterType: 'agile',
    name: '死神貴族',
    flavor: '速度快，會招喚同伴並使用即死咒文(查基)。',
    emoji: '💀👑',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 31,
    baseHp: 360,
    baseMp: 35,
    baseAttributes: {
      attack: 72,
      vitality: 28,
      defense: 48,
      recovery: 108,
      magic: 122,
      agility: 45,
    },
    growthPerLevel: {
      attack: 5.5,
      vitality: 4.0,
      defense: 4.5,
      recovery: 1.5,
      magic: 4.5,
      agility: 9.0,
    },
    skills: [
      { id: 'slash_2', probability: 0.2 },
    ],
    goldDrop: 160,
    },
  {
    id: 'emperor_slime',
    tier: 5,
    monsterType: 'average',
    name: '史萊姆帝王',
    flavor: '史萊姆界的皇族，防禦、HP、MP都極高，會使用各種輔助魔法。',
    emoji: '👑👑🟦',
    sizeLevel: 4, // 120% - 大型怪物（帝王級）
    baseXp: 55,
    baseHp: 450,
    baseMp: 250,
    baseAttributes: {
      attack: 90,
      vitality: 40,
      defense: 90,
      recovery: 22,
      magic: 22,
      agility: 18,
    },
    growthPerLevel: {
      attack: 4.1,
      vitality: 4.0,
      defense: 4.1,
      recovery: 4.5,
      magic: 4.5,
      agility: 3.5,
    },
    skills: [
      { id: 'slash_4', probability: 0.2 },
      { id: 'iceball_4', probability: 0.2 },
      { id: 'explosion_4', probability: 0.2 },
      { id: 'mass_heal_2', probability: 0.2 },
    ],
    goldDrop: 160,
    },
  {
    id: 'zoma',
    tier: 5,
    monsterType: 'boss',
    name: '大魔王佐瑪',
    flavor: '擁有凍結波動消除我方Buff，與強力的冰系最強咒文。',
    emoji: '👑❄️',
    sizeLevel: 4, // 120% - 大型boss（大魔王）
    baseXp: 500,
    baseHp: 2500,
    baseMp: 250,
    actionsPerTurn: 2, // 每回合行動2次
    baseAttributes: {
      attack: 170,
      vitality: 100,
      defense: 140,
      recovery: 20,
      magic: 55,
      agility: 85,
    },
    growthPerLevel: {
      attack: 5.3,
      vitality: 5.0,
      defense: 5.0,
      recovery: 4.0,
      magic: 10.0,
      agility: 4.0,
    },
    skills: [
      { id: 'fireball_3', probability: 0.3 },
      { id: 'iceball_3', probability: 0.3 },
      { id: 'explosion_3', probability: 0.2 },
    ],
    goldDrop: 1600,
    // 多形態boss：當HP降到50%時切換形態
    forms: [
      {
        // 第一形態：冰霜形態
        name: '大魔王佐瑪（冰霜形態）',
        emoji: '👑❄️',
        baseAttributes: {
          attack: 170,
          vitality: 100,
          defense: 140,
          recovery: 20,
          magic: 55,
          agility: 85,
        },
        growthPerLevel: {
          attack: 5.3,
          vitality: 5.0,
          defense: 5.0,
          recovery: 4.0,
          magic: 10.0,
          agility: 4.0,
        },
        skills: [
          { id: 'fireball_3', probability: 0.3 },
          { id: 'iceball_3', probability: 0.3 },
          { id: 'explosion_3', probability: 0.2 },
        ],
      },
      {
        // 第二形態：極寒形態
        name: '大魔王佐瑪（極寒形態）',
        emoji: '👑❄️💀',
        baseAttributes: {
          attack: 200,
          vitality: 120,
          defense: 160,
          recovery: 30,
          magic: 80,
          agility: 100,
        },
        growthPerLevel: {
          attack: 6.5,
          vitality: 6.0,
          defense: 6.0,
          recovery: 5.0,
          magic: 12.0,
          agility: 5.0,
        },
        skills: [
          { id: 'iceball_5', probability: 0.4 },
          { id: 'explosion_3', probability: 0.3 },
          { id: 'mass_heal_2', probability: 0.2 },
        ],
      },
    ],
    transformHpThreshold: 0.05, // HP降到5%時切換形態
    },
  
  // ========== 階層 6：隱藏迷宮 ==========
  {
    id: 'hell_gladiator',
    tier: 6,
    monsterType: 'attack',
    name: '地獄猛將',
    flavor: '四隻手都持武器，一回合可能攻擊4次，物理輸出的頂點。',
    emoji: '⚔️⚔️',
    sizeLevel: 4, // 120% - 大型怪物
    baseXp: 130,
    baseHp: 550,
    baseMp: 25,
    baseAttributes: {
      attack: 155,
      vitality: 50,
      defense: 105,
      recovery: 8,
      magic: 6,
      agility: 20,
    },
    growthPerLevel: {
      attack: 5.0,
      vitality: 5.0,
      defense: 5.0,
      recovery: 1.5,
      magic: 1.2,
      agility: 4.0,
    },
    skills: [
      { id: 'rapidity_strike_3', probability: 0.9 },
    ],
    goldDrop: 220,
    },
  {
    id: 'pandoras_box',
    tier: 6,
    monsterType: 'defense',
    name: '潘朵拉盒',
    flavor: '寶箱怪的頂點，防禦極高，會使用致死魔法與全體睡眠。',
    emoji: '📦',
    sizeLevel: 2, // 80% - 中等大小
    baseXp: 128,
    baseHp: 450,
    baseMp: 40,
    baseAttributes: {
      attack: 140,
      vitality: 70,
      defense: 145,
      recovery: 15,
      magic: 18,
      agility: 10,
    },
    growthPerLevel: {
      attack: 5.5,
      vitality: 5.0,
      defense: 5.4,
      recovery: 3.0,
      magic: 3.5,
      agility: 2.0,
    },
    skills: [
      { id: 'defense_shield_t5', probability: 0.2 },
      { id: 'defense_shield_t6', probability: 0.2 },
    ],
    goldDrop: 220,
    },
  {
    id: 'wight_king',
    tier: 6,
    monsterType: 'magic',
    name: '死靈之王',
    flavor: '魔法造詣登峰造極，會使用全遊戲最強的屬性咒文。',
    emoji: '👑💀',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 129,
    baseHp: 200,
    baseMp: 120,
    baseAttributes: {
      attack: 25,
      vitality: 35,
      defense: 25,
      recovery: 215,
      magic: 60,
      agility: 22,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 6.5,
      defense: 5.0,
      recovery: 3.0,
      magic: 6.0,
      agility: 4.5,
    },
    skills: [
      { id: 'fireball_5', probability: 0.2 },
      { id: 'explosion_3', probability: 0.2 },
    ],
    goldDrop: 220,
    },
  {
    id: 'twilightmare',
    tier: 6,
    monsterType: 'recovery',
    name: '夢魘獨角獸',
    flavor: '速度快且能使用全體完全恢復(貝霍瑪珍)，是最難纏的補師。',
    emoji: '🦄',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 128,
    baseHp: 300,
    baseMp: 90,
    baseAttributes: {
      attack: 35,
      vitality: 55,
      defense: 30,
      recovery: 50,
      magic: 35,
      agility: 28,
    },
    growthPerLevel: {
      attack: 6.5,
      vitality: 10.0,
      defense: 6.0,
      recovery: 10.0,
      magic: 7.0,
      agility: 5.5,
    },
    skills: [
      { id: 'heal_5', probability: 0.2 },
      { id: 'mass_heal_3', probability: 0.2 },
    ],
    goldDrop: 220,
    },
  {
    id: 'prism_peacock',
    tier: 6,
    monsterType: 'agile',
    name: '彩虹孔雀',
    flavor: '速度凌駕於所有職業之上，會使用強烈的光系特技。',
    emoji: '🦚',
    sizeLevel: 3, // 100% - 正常大小
    baseXp: 131,
    baseHp: 240,
    baseMp: 45,
    baseAttributes: {
      attack: 128,
      vitality: 40,
      defense: 94,
      recovery: 12,
      magic: 30,
      agility: 160,
    },
    growthPerLevel: {
      attack: 4.5,
      vitality: 4.5,
      defense: 4.5,
      recovery: 2.5,
      magic: 4.0,
      agility: 12.0,
    },
    skills: [
      { id: 'slash_5', probability: 0.2 },
    ],
    goldDrop: 320,
    },
  {
    id: 'metal_king_slime',
    tier: 6,
    monsterType: 'average',
    name: '金屬史萊姆王',
    flavor: '雖然HP不高，但擁有近乎無敵的防禦與全屬性免疫，經驗值極高。',
    emoji: '👑🟦✨',
    sizeLevel: 2, // 80% - 中等大小（雖然是王但體型不大）
    baseXp: 125,
    baseHp: 100,
    baseMp: 60,
    baseAttributes: {
      attack: 40,
      vitality: 10,
      defense: 285,
      recovery: 30,
      magic: 530,
      agility: 25,
    },
    growthPerLevel: {
      attack: 5.5,
      vitality: 3.0,
      defense: 5.0,
      recovery: 6.0,
      magic: 5.0,
      agility: 5.0,
    },
    skills: [
      { id: 'slash_5', probability: 0.2 },
      { id: 'mass_heal_3', probability: 0.2 },
    ],
    goldDrop: 320,
    },
  {
    id: 'darkream',
    tier: 6,
    monsterType: 'boss',
    name: '黑暗多雷姆',
    flavor: '破壞神，實力凌駕於魔王之上，擁有所有最強特技的隱藏Boss。',
    emoji: '👑💀🔥',
    sizeLevel: 4, // 120% - 大型boss（破壞神）
    baseXp: 3000,
    baseHp: 4000,
    baseMp: 200,
    baseAttributes: {
      attack: 100,
      vitality: 150,
      defense: 60,
      recovery: 30,
      magic: 80,
      agility: 50,
    },
    growthPerLevel: {
      attack: 18.0,
      vitality: 28.0,
      defense: 12.0,
      recovery: 6.0,
      magic: 15.0,
      agility: 10.0,
    },
    skills: [
      { id: 'slash_5', probability: 0.2 },
      { id: 'fireball_5', probability: 0.2 },
      { id: 'explosion_3', probability: 0.2 },
    ],
    goldDrop: 3200,
    // 多形態boss：當HP降到50%時切換形態
    forms: [
      {
        // 第一形態：破壞形態
        name: '黑暗多雷姆（破壞形態）',
        emoji: '👑💀🔥',
        baseAttributes: {
          attack: 100,
          vitality: 150,
          defense: 60,
          recovery: 30,
          magic: 80,
          agility: 50,
        },
        growthPerLevel: {
          attack: 18.0,
          vitality: 28.0,
          defense: 12.0,
          recovery: 6.0,
          magic: 15.0,
          agility: 10.0,
        },
        skills: [
          { id: 'slash_5', probability: 0.2 },
          { id: 'fireball_5', probability: 0.2 },
          { id: 'explosion_3', probability: 0.2 },
        ],
      },
      {
        // 第二形態：終極形態
        name: '黑暗多雷姆（終極形態）',
        emoji: '👑💀🔥⚡',
        baseAttributes: {
          attack: 150,
          vitality: 200,
          defense: 100,
          recovery: 50,
          magic: 120,
          agility: 80,
        },
        growthPerLevel: {
          attack: 25.0,
          vitality: 35.0,
          defense: 18.0,
          recovery: 10.0,
          magic: 22.0,
          agility: 15.0,
        },
        skills: [
          { id: 'slash_5', probability: 0.25 },
          { id: 'fireball_5', probability: 0.25 },
          { id: 'explosion_3', probability: 0.25 },
          { id: 'mass_heal_2', probability: 0.15 },
        ],
        actionsPerTurn: 3, // 第二形態每回合行動3次
      },
    ],
    transformHpThreshold: 0.05, // HP降到5%時切換形態
    },
];
  window.GameData = window.GameData || {};
  window.GameData.ENEMY_DECK = ENEMY_DECK;
})();
